# config map backend
apiVersion: v1
kind: ConfigMap
metadata:
  name: agenda-backend-configmap
  namespace: agenda-namespace
data: 
  STAGE: "dev" 
  PORT: "3000"
  URL: "http://localhost:3000"
  POSTGRES_USER: "agenda-u"
  POSTGRES_HOST: "agenda-db-pg"
  POSTGRES_DB: "agenda-db"
  POSTGRES_PASSWORD: "agenda-db"
  POSTGRES_PORT: "5432"
  MAIL_HOST: "sandbox.smtp.mailtrap.io"
  MAIL_PORT: "2525"
  MAIL_USER: "75883cf4e9bba6"
  MAIL_PASS: "4e62f318c3763e"
  JWT_SEED: "s33d1nf0"
  REDIS_HOST: "agenda-db-redis"
  REDIS_PORT: "6379"
---
# pod backend

apiVersion: v1
kind: Pod
metadata: 
  name: agenda-backend-pod
  namespace: agenda-namespace
# especificaciones del contenedor
spec:
  containers:
    - name: agenda-backend-pod-container
      image: rbmoises/devops:agenda-backend-v1
      envFrom:
        - configMapRef:
            name: agenda-backend-configmap
      ports:
        - containerPort: 3000
      resources:
        limits:
          memory: "500Mi"
          cpu: "500m"
