apiVersion: v1
kind: Pod
metadata: 
  name: agenda-redis-pod
  namespace: agenda-namespace
spec: 
  containers:
    - name: agenda-redis-pod-container
      image: redis:alpine
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "128m"
          memory: "128Mi"
      