apiVersion: apps/v1
kind: Deployment
metadata: 
  name: agenda-backend-deployment
  namespace: agenda-namespace
  labels:
    app: agenda-backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agenda-backend-app
  template:
    metadata:
      labels:
        app: agenda-backend-app
    spec:
      containers:
        - name: agenda-backend-deployment-container
          image: rbmoises/devops:agenda-backend-v2
          volumeMounts:
            - name: env-file
              mountPath: /app/.env
              subPath: .env
          # envFrom:
          #   - configMapRef:
          #       name: agenda-backend-configmap
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
      volumes:
        - name: env-file
          configMap:  
            name: agenda-backend-configmap
