
apiVersion: v1
kind: Service
metadata:
  name: agenda-postgres-app
  namespace: agenda-namespace
spec:
  type: NodePort
  selector:
    app: agenda-postgres-app
  ports:
    - port: 5432
      targetPort: 5432