apiVersion: v1
kind: Service
metadata:
  name: agenda-frontend-app
  namespace: agenda-namespace
spec:
  type: NodePort
  selector:
    app: agenda-frontend-app
  ports:
    - port: 3001
      targetPort: 3000