# This is a basic workflow to help you get started with Actions

name: CI
# Controls when the workflow will run
on:
  # ejecutar de forma manual el pipeline
  workflow_dispatch:
# ejecutar los trabajos que se deseán realizar, esto se ejecutan de forma secuencial
jobs:
  # primer workflow, lo llamaremos CI
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: PRIMER PASO DEL SCRIPT
        run: echo Hello, world!
  cd: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SEGUNDO PASO DEL SCRIPT
      - run: echo segundo paso del script..  en ejecución
