name: CI
on:
  workflow_dispatch:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PRIMER PASO DEL SCRIPT
        run: echo Hello, world!

  cd: 
    runs-on: ubuntu-latest
    need: [ci]
    steps:
      - uses: actions/checkout@v4
      - name: SEGUNDO PASO 
        run: echo SEGUNDO PASO EN EJECUCION...!
